# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_dev.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pycodestyle ~/repo/tfschmuck/server
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  push:
    machine: true
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: build docker image
          command: |
            docker build -t bfriedrichs/tfschmuck .
      - run: |
        name: docker login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push to docker.io
          command: |
            docker push bfriedrichs/tfschmuck

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: master