- hosts: webserver
  become: true

  tasks:
  - name: copy config file
    block:
      - template:
          src: templates/config.yml.jinja
          dest: /etc/tfschmuck.yml

  - name: pull image
    docker_image:
      name: bfriedrichs/tfschmuck
      force: true

  - name: start container
    docker_container:
      name: tfschmuck
      image: bfriedrichs/tfschmuck
      env:
        LETSENCRYPT_EMAIL: bjoern@friedrichs1.de
        LETSENCRYPT_HOST: tfschmuck.bjoern-friedrichs.de
        VIRTUAL_HOST: tfschmuck.bjoern-friedrichs.de

  - name: Copy config
    shell: docker cp /etc/tfschmuck.yml tfschmuck:/etc/tfschmuck.yml